apiVersion: v1
kind: Pod
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: discobats-client-test
  name: discobats-client-test
  namespace: default
spec:
  containers:
    - image: skatze/discobats:client_alpine
      imagePullPolicy: IfNotPresent
      name: discobats
      resources: { }
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      tty: true
      stdin: true
      ports:
        - name: remotedebugging
          containerPort: 5005
          protocol: TCP
  serviceAccountName: discobats
  dnsPolicy: ClusterFirst
  restartPolicy: Never
